import "server-only";
import { existsSync } from "node:fs";
import path from "node:path";
import type { Locale } from "@/lib/locales";
import { renderRobots, renderSite, renderSitemap } from "@/lib/render";
import type { Site } from "@/lib/site";
import { UPLOAD_DIR } from "./db";

/**
 * Builds the static file set for a site, one document per enabled language.
 *
 * Shape (requirement 16 — a real localised URL structure, not a JS text swap):
 *
 *   /index.html          redirects to the default language
 *   /en/index.html       English
 *   /el/index.html       Greek
 *   /images/<id>.webp    shared, so a second language costs no extra bytes
 *   /sitemap.xml         one entry per language, cross-linked with hreflang
 *   /robots.txt
 *
 * A single-language site still gets its locale folder, so adding a language
 * later never changes the URL of the existing one.
 */

export type BundleFile =
  | { kind: "text"; name: string; content: string }
  | { kind: "file"; name: string; source: string };

export function imageIdsFor(site: Site): string[] {
  const ids = new Set<string>();
  if (site.meta.logo) ids.add(site.meta.logo.assetId);
  for (const s of site.sections) {
    if (s.type === "gallery") s.imageIds.forEach((i) => ids.add(i));
    if (s.type === "hero" && s.imageId) ids.add(s.imageId);
    if (s.type === "about" && s.imageId) ids.add(s.imageId);
    if (s.type === "menu") {
      for (const c of s.categories) for (const i of c.items) if (i.imageId) ids.add(i.imageId);
    }
  }
  return [...ids];
}

/**
 * `baseUrl` is used for canonical, hreflang and sitemap URLs. When it is not
 * known (a plain ZIP the user may host anywhere) the pages fall back to
 * relative links between languages, which still work from the filesystem.
 */
export function buildBundle(site: Site, baseUrl?: string): BundleFile[] {
  const files: BundleFile[] = [];
  const abs = baseUrl?.replace(/\/+$/, "");

  const localeUrl = (l: Locale) => (abs ? `${abs}/${l}/` : `/${l}/`);

  for (const locale of site.meta.locales) {
    // Relative hrefs keep the switcher working when the ZIP is opened from a
    // file:// path or hosted under any prefix.
    const localeHref = (l: Locale) => (l === locale ? "./" : `../${l}/`);

    const html = renderSite(site, {
      locale,
      assetUrl: (id) => `../images/${id}.webp`,
      localeHref: abs ? (l) => localeUrl(l) : localeHref,
      canonical: abs ? localeUrl(locale) : undefined,
      baseUrl: abs,
    });
    files.push({ kind: "text", name: `${locale}/index.html`, content: html });
  }

  // Root document: sends a visitor to the default language without JavaScript
  // where possible, and never leaves a blank page if meta refresh is blocked.
  const def = site.meta.defaultLocale;
  files.push({
    kind: "text",
    name: "index.html",
    content: `<!doctype html>
<html lang="${def}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<title>${escapeHtml(site.meta.businessName)}</title>
<link rel="canonical" href="${escapeHtml(abs ? localeUrl(def) : `./${def}/`)}">
${site.meta.locales.map((l) => `<link rel="alternate" hreflang="${l}" href="${escapeHtml(abs ? localeUrl(l) : `./${l}/`)}">`).join("\n")}
<link rel="alternate" hreflang="x-default" href="${escapeHtml(abs ? localeUrl(def) : `./${def}/`)}">
<meta http-equiv="refresh" content="0; url=./${def}/">
<script>(function(){try{
// A returning visitor goes back to the language they last chose. Only the
// root document does this, so every language URL stays stable and crawlable.
var l=localStorage.getItem('wg-lang');
var ok=${JSON.stringify(site.meta.locales)};
if(l&&ok.indexOf(l)>-1&&l!==${JSON.stringify(def)}){location.replace('./'+l+'/');}
}catch(e){}})();</script>
</head>
<body style="font-family:system-ui;padding:2rem">
<p><a href="./${def}/">${escapeHtml(site.meta.businessName)}</a></p>
${site.meta.locales.length > 1 ? `<ul>${site.meta.locales.map((l) => `<li><a href="./${l}/" hreflang="${l}">${l.toUpperCase()}</a></li>`).join("")}</ul>` : ""}
</body>
</html>`,
  });

  files.push({
    kind: "text",
    name: "sitemap.xml",
    content: renderSitemap(site, (l) => (abs ? localeUrl(l) : `/${l}/`)),
  });
  files.push({
    kind: "text",
    name: "robots.txt",
    content: renderRobots(abs ? `${abs}/sitemap.xml` : "/sitemap.xml"),
  });
  files.push({
    kind: "text",
    name: "README.md",
    content: `# ${site.meta.businessName}

Generated by Website Generator.

Languages: ${site.meta.locales.join(", ")} (default: ${site.meta.defaultLocale})

Upload the contents of this folder to any static host. \`index.html\` sends
visitors to the default language; each language lives in its own folder and
carries its own metadata, canonical URL and hreflang links.
`,
  });

  for (const id of imageIdsFor(site)) {
    const source = path.join(UPLOAD_DIR, `${id}.webp`);
    if (existsSync(source)) files.push({ kind: "file", name: `images/${id}.webp`, source });
  }

  return files;
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;").replace(/'/g, "&#39;");
}
