import archiver from "archiver";
import { createReadStream } from "node:fs";
import { existsSync } from "node:fs";
import path from "node:path";
import { getCurrentUser } from "@/server/auth";
import { getProject } from "@/server/projects";
import { UPLOAD_DIR } from "@/server/db";
import { renderSite } from "@/lib/render";

/**
 * Streams the finished website as a ZIP (requirement 12).
 *
 * Streaming rather than buffering matters here: on a phone the download starts
 * immediately and the server never holds the whole archive in memory.
 * `Content-Disposition: attachment` hands the file to the phone's own download
 * / share sheet, which is exactly what the requirement asks for.
 */
export async function GET(_req: Request, ctx: { params: Promise<{ id: string }> }) {
  const user = await getCurrentUser();
  if (!user) return new Response("Not signed in", { status: 401 });

  const { id } = await ctx.params;
  const project = getProject(id, user.id);
  if (!project?.site) return new Response("Nothing to export yet", { status: 404 });

  const site = project.site;
  // Images are exported alongside the HTML and referenced relatively, so the
  // ZIP is a complete, self-contained site that works offline.
  const html = renderSite(site, { assetUrl: (assetId) => `images/${assetId}.webp` });

  const archive = archiver("zip", { zlib: { level: 9 } });
  archive.append(html, { name: "index.html" });
  archive.append(
    `# ${site.meta.businessName}\n\nGenerated by Website Generator.\n\n` +
      `Open index.html in a browser, or upload the contents of this folder to any static host.\n`,
    { name: "README.md" },
  );
  archive.append(
    "User-agent: *\nAllow: /\n",
    { name: "robots.txt" },
  );

  const imageIds = new Set<string>();
  for (const section of site.sections) {
    if (section.type === "gallery") section.props.imageIds.forEach((i) => imageIds.add(i));
    if (section.type === "hero" && section.props.imageId) imageIds.add(section.props.imageId);
    if (section.type === "about" && section.props.imageId) imageIds.add(section.props.imageId);
  }
  for (const assetId of imageIds) {
    const file = path.join(UPLOAD_DIR, `${assetId}.webp`);
    if (existsSync(file)) archive.append(createReadStream(file), { name: `images/${assetId}.webp` });
  }

  void archive.finalize();

  const slug =
    site.meta.businessName.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") ||
    "website";

  return new Response(archive as unknown as ReadableStream, {
    headers: {
      "Content-Type": "application/zip",
      "Content-Disposition": `attachment; filename="${slug}.zip"`,
      "Cache-Control": "no-store",
    },
  });
}

export const dynamic = "force-dynamic";
